// Module included in the following assemblies:
//
// * logging/config/cluster-logging-maintenance-support.adoc

:_content-type: CONCEPT
[id="cluster-logging-maintenance-support-about_{context}"]
= About unsupported configurations

The supported way of configuring the {logging-title} is by configuring it using the options described in this documentation. Do not use other configurations, as they are unsupported. Configuration paradigms might change across {product-title} releases, and such cases can only be handled gracefully if all configuration possibilities are controlled. If you use configurations other than those described in this documentation, your changes will disappear because the OpenShift Elasticsearch Operator and Red Hat OpenShift Logging Operator reconcile any differences. The Operators reverse everything to the defined state by default and by design.

[NOTE]
====
 A new revision of the Kubernetes API server will only roll out if the API server named certificate are added for the first time. If the named certificate is renewed or modified later then the Kubernetes API server will not roll out to new revision
====
